### ISSUE TITLE
Update docs to make clear need for `/api` in endpoint requests

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/Docs#16]
I recently ran into an issue where I attempted to follow the documentation's advice and make endpoint requests using `https://data-sources.pdap.io/`.

However, I soon learned that attempting to do it like that from a simple programmatic request doesn't work. Instead, all endpoints need to be preceded by `https://data-sources.pdap.io/api`. This isn't mentioned in the documentation. 

The documentation should be amended to include that.

**Comment by josh-chamberlain** [comment]
fixed with a gitbook PR: https://app.gitbook.com/o/-MXypK5ySzExtEzQU6se/s/-MXyolqTg_voOhFyAcr-/~/changes/495/api/endpoints/admin/~/overview
